Code/Argus/Models/Procedimento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace Argus.Models
{
    public class Procedimento
    {
        private Contexto db = new Contexto();

        [Key]
        public int CODIGO { get; set; }

        [Display(Name = "Nome do procedimento")]
        [Required(ErrorMessage = "Por favor preencher o Nome do Procedimento")]
        [StringLength(60)]
        [MaxLength(60)]
        public string NOME { get; set; }

        [Display(Name = "Descrição")]
        [Required(ErrorMessage = "Por favor preencher a Descrição do Procedimento")]        
        public string DESCRICAO { get; set; }

        public void Incluir(Procedimento procedimento)
        {
            db.Procedimento.Add(procedimento);
            db.SaveChanges();
        }

        public void Atualizar(Procedimento procedimento)
        {
            db.Entry(procedimento).State = EntityState.Modified;
            db.SaveChanges();
        }

        public void Eliminar(Procedimento procedimento)
        {
            db.Entry(procedimento).State = EntityState.Deleted;
            db.SaveChanges();
        }

        public Procedimento Busca(int id)
        {
            return db.Procedimento.Find(id);
        }

        public List<Procedimento> ListaProcedimentos(String pesquisa)
        {
            var procedimento = (from a in db.Procedimento
                          where a.DESCRICAO.StartsWith(pesquisa)
                          select a).Take(50).ToList();
            return procedimento;
        }
    }
}

Code/Argus/Controllers/ProcedimentoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Argus.Models;
using System.IO;
using System.Web.Helpers;

namespace Argus.Controllers
{
    [Authorize]
    public class ProcedimentoController : Controller
    {
        private Contexto db = new Contexto();

        public ActionResult Listar(String pesquisa = "")
        {
            Procedimento procedimento = new Procedimento();
            return View(procedimento.ListaProcedimentos(pesquisa));
        }

        public ActionResult Incluir()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Incluir(Procedimento procedimento, HttpPostedFileBase file)
        {

            if (ModelState.IsValid)
            {                
                procedimento.Incluir(procedimento);
                return RedirectToAction("Listar");
            }
            else
                return View(procedimento);
        }

        public ActionResult Editar(int codigo)
        {
            Procedimento procedimento = db.Procedimento.Find(codigo);
            return View(procedimento);
        }

        [HttpPost]
        public ActionResult Editar(Procedimento procedimento)
        {
            if (ModelState.IsValid)
            {
                procedimento.Atualizar(procedimento);
                return RedirectToAction("Listar");
            }
            else
                return View(procedimento);
        }

        public ActionResult Eliminar(int codigo)
        {
            Procedimento procedimento = db.Procedimento.Find(codigo);
            return View(procedimento);
        }

        [HttpPost]
        public ActionResult Eliminar(Procedimento procedimento)
        {
            procedimento.Eliminar(procedimento);
            return RedirectToAction("Listar");
        }

        public ActionResult Imprimir(int codigo=0, int codigoanimal=0)
        {
            ViewBag.ListaAnimal = new SelectList(db.Animal, "CODIGO", "NOME");
            Procedimento procedimento = db.Procedimento.Find(codigo);
            if (codigoanimal != 0)
            {
                Animal animal = db.Animal.Find(codigoanimal);
                ViewBag.CodigoAnimal = animal.CODIGO.ToString();
                ViewBag.NomeAnimal = animal.NOME;
                ViewBag.DataNascimento = animal.DT_NASCIMENTO.ToString();
                ViewBag.NomeCliente = animal.Cliente.Pessoa.NOME;
                if (animal.Veterinario != null) { 
                    ViewBag.NomeVeterinario = animal.Veterinario.Pessoa.NOME;
                    ViewBag.CRMV = animal.Veterinario.CRMV;
                } 
                else { 
                    ViewBag.NomeVeterinario = "";
                    ViewBag.CRMV = "";
                }
                
                ViewBag.EnderecoCliente = animal.Cliente.Pessoa.ENDERECO;
                ViewBag.DataHora = DateTime.Now.ToString();
            }
            return View(procedimento);
        }

        public ActionResult ImprimirProc(int codigo = 0, int codigoanimal = 0)
        {
            Procedimento procedimento = db.Procedimento.Find(codigo);

            Animal animal = db.Animal.Find(codigoanimal);
            ViewBag.NomeAnimal = animal.NOME;
            ViewBag.DataNascimento = animal.DT_NASCIMENTO.ToString();
            ViewBag.NomeCliente = animal.Cliente.Pessoa.NOME;
            if (animal.Veterinario != null)
            {
                ViewBag.NomeVeterinario = animal.Veterinario.Pessoa.NOME;
                ViewBag.CRMV = animal.Veterinario.CRMV;
            }
            else
            {
                ViewBag.NomeVeterinario = "";
                ViewBag.CRMV = "";
            }
            ViewBag.EnderecoCliente = animal.Cliente.Pessoa.ENDERECO;
            ViewBag.DataHora = DateTime.Now.ToString();
            return View(procedimento);
        }
    }
}

Code/Argus/Views/Procedimento/Editar.cshtml
@model Argus.Models.Procedimento

<h2>Edição</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="../../Scripts/jquery-1.6.min.js" type="text/javascript"></script>
<script src="../../Scripts/jquery.maskedinput-1.3.min.js" type="text/javascript"></script>
<script src="../../Scripts/FuncoesGenericas.js" type="text/javascript"></script>


@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)

        <table>

        <tr>
        <td>@Html.LabelFor(model => model.NOME)</td>
        <td colspan="2">@Html.TextBoxFor(model => model.NOME, new { maxlength = 60, Class = "textomediorequerido" }) @Html.ValidationMessageFor(model => model.NOME)</td>
        </tr>
              
        <tr rowspan="2">
        <td>@Html.LabelFor(model => model.DESCRICAO)</td>      
        <td>@Html.TextAreaFor(model => model.DESCRICAO, new {  cols = "60%", rows = "15%" }) @Html.ValidationMessageFor(model => model.DESCRICAO)</td>  

        <td align="center">Selecionar Campos<br />
           <select id="dropdown" size="11">
           <option value="0" selected="selected">[Nome do Animal]</option>
           <option value="1">[Data de nascimento Animal]</option>
           <option value="2">[Nome do Cliente]</option>
           <option value="3">[Nome do Veterinário]</option>
           <option value="4">[CRMV do Veterinário]</option>
           <option value="5">[Endereço do Cliente]</option>            
           <option value="6">[Data Atual]</option> 
           </select>
           <br/><br />
           <input type="button" value="Incluir no Procedimento"  onclick="insert(this.form.DESCRICAO,$('#dropdown option:selected').text())"> 
        </td>
        </tr>                         

        </table>
         
        <p><input type="submit" value="Gravar" /></p>   
}   

Code/Argus/Views/Procedimento/Eliminar.cshtml
@model Argus.Models.Procedimento

<h2>Eliminação</h2>

@using (Html.BeginForm())
{    
        <table>
        
        <tr>
        <td>@Html.LabelFor(model => model.NOME)</td>
        <td>@Html.EditorFor(model => model.NOME) @Html.ValidationMessageFor(model => model.NOME)</td>
        </tr>
         
        </table>
    
        <p> <input type="submit" value="Eliminar" /> </p>
}

<div>
    @Html.ActionLink("Voltar", "Listar")
</div>

Code/Argus/Views/Procedimento/Imprimir.cshtml
@model Argus.Models.Procedimento           
           
<h2>Impressão</h2>

<script src="../../Scripts/jquery.js" type="text/javascript"></script>

<script type="text/javascript">
    function substituiProc(valor) {
    var str = valor;
    str = str.replace("[Nome do Animal]", '@(ViewBag.NomeAnimal)');
    str = str.replace("[Data de nascimento Animal]", '@(ViewBag.DataNascimento)');
    str = str.replace("[Nome do Cliente]", '@(ViewBag.NomeCliente)');
    str = str.replace("[Nome do Veterinário]", '@(ViewBag.NomeVeterinario)');
    str = str.replace("[CRMV do Veterinário]", '@(ViewBag.CRMV)');
    str = str.replace("[Endereço do Cliente]", '@(ViewBag.EnderecoCliente)');
    str = str.replace("[Data Atual]", '@(ViewBag.DataHora)');
    $("#DESCRICAO").val(str);
}

function validarPesquisa() {
    if ('@(ViewBag.CodigoAnimal)' == "") {
        alert('Por favor selecionar o animal e preencher o procedimento antes de efetuar a impressão');
        return false;
    }else 
        return true;
}
</script>

@using (Html.BeginForm("Imprimir", "Procedimento"))
{
    @Html.TextBoxFor(model => model.CODIGO, new { Type = "hidden" }) 
    @Html.DisplayText("Informe o nome do animal:")
    @Html.DropDownList("codigoanimal", ViewBag.ListaAnimal as SelectList, new { @style = "width: 355px;" })
    <input type="submit" value="Preencher Procedimento"/>
    <br />
    <br />
}

<body onload = "substituiProc(DESCRICAO.value)" >
@using (Html.BeginForm("ImprimirProc", "Procedimento"))
{           
    @Html.TextBoxFor(model => model.CODIGO, new { Type = "hidden" }) 
    @Html.TextBox("codigoanimal", (string)ViewBag.CodigoAnimal, new { Type = "hidden" })
    <table>
        <tr><td align="center">@Html.DisplayFor(model => model.NOME)<br /><br /></td></tr>
        <tr><td>@Html.TextAreaFor(model => model.DESCRICAO, new { Name = "DESCRICAO", cols = "60%", rows = "15%" })</td></tr>
    </table>
    <input type="submit" id="meu" value="Imprimir" onclick = "return validarPesquisa();"/>
}
</body> 
<div>
    <br /><br />
    @Html.ActionLink("Voltar a Listagem de Procedimentos", "Listar")
</div>

Code/Argus/Views/Procedimento/ImprimirProc.cshtml
@model Argus.Models.Procedimento     
           
@{
   
    Layout = "~/Views/Shared/_LayoutImp.cshtml";
}

<head>
<style type="text/css">
table
{
    border-collapse: collapse;
    border:1px solid ;
    font-family: Verdana, Arial, Helvetica, sans-serif;border: 1px solid black;
    width:90%;
}
td,tr,textarea
{
    border:none ;
}

</style>
</head>


<script src="../../Scripts/jquery.js" type="text/javascript"></script>

<script type="text/javascript">
    function substituiProc(valor) {
        var str = valor;
        str = str.replace("[Nome do Animal]", '@(ViewBag.NomeAnimal)');
        str = str.replace("[Data de nascimento Animal]", '@(ViewBag.DataNascimento)');
        str = str.replace("[Nome do Cliente]", '@(ViewBag.NomeCliente)');
        str = str.replace("[Nome do Veterinário]", '@(ViewBag.NomeVeterinario)');
        str = str.replace("[CRMV do Veterinário]", '@(ViewBag.CRMV)');
        str = str.replace("[Endereço do Cliente]", '@(ViewBag.EnderecoCliente)');
        str = str.replace("[Data Atual]", '@(ViewBag.DataHora)');
        $("#DESCRICAO").val(str);
    } 
</script>

<body onload = "substituiProc(DESCRICAO.value)" >
<br />
<table>
    <tr align="center"><td>@Html.DisplayFor(model => model.NOME)<br /><br /></td></tr>
    <tr><td>@Html.TextAreaFor(model => model.DESCRICAO, new { Name = "DESCRICAO", cols = "60%", rows = "25%" })</td></tr>
 </table>
 </body>

 <div>
    <br /><br />
    @Html.ActionLink("Voltar a Listagem de Procedimentos", "Listar")
</div>

Code/Argus/Views/Procedimento/Incluir.cshtml
@model Argus.Models.Procedimento

<h2>Inclusão</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="../../Scripts/jquery-1.6.min.js" type="text/javascript"></script>
<script src="../../Scripts/jquery.maskedinput-1.3.min.js" type="text/javascript"></script>
<script src="../../Scripts/FuncoesGenericas.js" type="text/javascript"></script>

@using (Html.BeginForm("Incluir", "Procedimento", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.ValidationSummary(true)
        <table>
        
        <tr>
        <td>@Html.LabelFor(model => model.NOME)</td>
        <td colspan="2">@Html.TextBoxFor(model => model.NOME, new { maxlength = 60, Class = "textomediorequerido" }) @Html.ValidationMessageFor(model => model.NOME)</td>
        </tr>
              
        <tr rowspan="2">
        <td>@Html.LabelFor(model => model.DESCRICAO)</td>      
        <td>@Html.TextAreaFor(model => model.DESCRICAO, new {  cols = "60%", rows = "15%" }) @Html.ValidationMessageFor(model => model.DESCRICAO)</td>  

        <td align="center">Selecionar Campos<br />
           <select id="dropdown" size="11">
           <option value="0" selected="selected">[Nome do Animal]</option>
           <option value="1">[Data de nascimento Animal]</option>
           <option value="2">[Nome do Cliente]</option>
           <option value="3">[Nome do Veterinário]</option>
           <option value="4">[CRMV do Veterinário]</option>
           <option value="5">[Endereço do Cliente]</option>            
           <option value="6">[Data Atual]</option> 
           </select>
           <br/><br />
           <input type="button" value="Incluir no Procedimento"  onclick="insert(this.form.DESCRICAO,$('#dropdown option:selected').text())"> 
        </td>
        </tr>             
 
        </table>
         
        <p><input type="submit" value="Gravar" /></p> 
}   

Code/Argus/Views/Procedimento/Listar.cshtml
@model IEnumerable<Argus.Models.Procedimento>
@{
    WebGrid grid = new WebGrid(source: Model, selectionFieldName: "SelectedRow", rowsPerPage: 20);      
}

<script src="@Url.Content("~/Scripts/jquery.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.tabify.js")" type="text/javascript"></script>
<script src="../../Scripts/FuncoesGenericas.js" type="text/javascript"></script>
<link href="../../Content/webgrid.css" rel="stylesheet" type="text/css" />

<table>
    <tr>
        <td>
             @using (Html.BeginForm("Listar", "Procedimento"))
             {
                 <div class="textomedio">@Html.DisplayText("Informe o nome do procedimento:")</div>
                 @Html.TextBox("pesquisa", "") 
                <input type="submit" value="Pesquisar" />
             }
            </td>
         <td>
            @Html.ActionLink("Incluir", "Incluir")
         </td>
    </tr>
    <tr>
    <td colspan="2" width="100%">
        @grid.GetHtml(
            tableStyle: "webgrid",
            headerStyle: "webgrid-header",
            footerStyle: "webgrid-footer",
            alternatingRowStyle: "webgrid-alternating-row",
            selectedRowStyle: "webgrid-selected-row",
            rowStyle: "webgrid-row-style",
            mode: WebGridPagerModes.FirstLast | WebGridPagerModes.NextPrevious,
            firstText: "Primeiro",
            previousText: "Anterior",
            nextText: "Próximo",
            lastText: "Último",
            columns: grid.Columns(
            grid.Column("NOME", header: "Nome", format: @<text><div class="colunanomepequeno">@item.NOME</div></text>),
            grid.Column("DESCRICAO", header: "Descrição", format: @<text><div class="colunaobservacao">@item.DESCRICAO</div></text>),
            grid.Column("Editar", header: "Editar", format: @<text><div class="colunanomepequeno">@Html.ActionLink("Editar", "Editar", new { codigo = item.CODIGO })</div></text>, canSort: false),
            grid.Column("Eliminar", header: "Eliminar", format: @<text><div class="colunanomepequeno">@Html.ActionLink("Eliminar", "Eliminar", new { codigo = item.CODIGO })</div></text>, canSort: false),
            grid.Column("Imprimir", header: "Imprimir", format: @<text><div class="colunanomepequeno">@Html.ActionLink("Imprimir", "Imprimir", new { codigo = item.CODIGO })</div></text>, canSort: false)
          )
        )                    
    </td>
    </tr>
</table>