Code/Argus/Models/ExameReferencia.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data;

namespace Argus.Models
{
    public class ExameReferencia
    {
        private Contexto db = new Contexto();
                
        [Key, Column(Order = 1)]
        [Display(Description = "Exame")]
        public int CODIGO_EXAME { get; set; }

        [Key, Column(Order = 2)]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CODIGO_ITEM { get; set; }       
                       
        [Display(Name = "Descrição")]
        [Required(ErrorMessage = "Por favor preencher o campo Descricao")]
        [StringLength(60)]
        public string DESCRICAO { get; set; }

        [Display(Name = "Unidades")]
        public string UNIDADES { get; set; }

        [Display(Name = "De")]
        public Nullable<int> DE { get; set; }

        [Display(Name = "Até")]
        public Nullable<int> ATE { get; set; }

        public void Incluir(ExameReferencia examereferencia)
        {
            db.ExameReferencia.Add(examereferencia);
            db.SaveChanges();
        }

        public void Atualizar(ExameReferencia examereferencia)
        {
            db.Entry(examereferencia).State = EntityState.Modified;
            db.SaveChanges();
        }

        public void Eliminar(ExameReferencia examereferencia)
        {
            db.Entry(examereferencia).State = EntityState.Deleted;
            db.SaveChanges();
        }

        public ExameReferencia Busca(int id)
        {
            return db.ExameReferencia.Find(id);
        }

        public List<ExameReferencia> ListarExameReferencia(String pesquisa)
        {
            var examereferencia = (from a in db.ExameReferencia
                               where a.DESCRICAO.StartsWith(pesquisa)
                               select a).Take(50).ToList();
            return examereferencia;
        }
    }

}

Code/Argus/Controllers/ExameReferenciaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Argus.Models;
using System.IO;

namespace Argus.Controllers
{
    public class ExameReferenciaController : Controller
    {
         private Contexto db = new Contexto();
        //
        // GET: /ExameReferencia/

        public ActionResult Listar(String pesquisa = "")
        {
            ExameReferencia examereferencia = new ExameReferencia();
            return View(examereferencia.ListarExameReferencia(pesquisa));
        }


        public ActionResult Incluir()
        {
            ViewBag.ListaeExames = new SelectList(db.Exame, "CODIGO", "NOME");
            return View();
        }

        [HttpPost]
        public ActionResult Incluir(ExameReferencia examereferencia)
        {
            if (ModelState.IsValid)
            {
                examereferencia.Incluir(examereferencia);
                return RedirectToAction("Listar");
            }
            else
                return View(examereferencia);
        }

        public ActionResult Editar(int codigo, int codigoitem)
        {
            ExameReferencia examereferencia = db.ExameReferencia.Find(codigo, codigoitem);
            ViewBag.ListaeExames = new SelectList(db.Exame, "CODIGO", "NOME");
            return View(examereferencia);
        }

        [HttpPost]
        public ActionResult Editar(ExameReferencia examereferencia)
        {
            if (ModelState.IsValid)
            {
                examereferencia.Atualizar(examereferencia);
                return RedirectToAction("Listar");
            }
            else
                return View(examereferencia);
        }

        public ActionResult Eliminar(int codigo, int codigoitem)
        {
            ExameReferencia examereferencia = db.ExameReferencia.Find(codigo, codigoitem);
            return View(examereferencia);
        }

        [HttpPost]
        public ActionResult Eliminar(ExameReferencia examereferencia)
        {
            examereferencia.Eliminar(examereferencia);
            return RedirectToAction("Listar");
        }
    }



}

Code/Argus/Views/ExameReferencia/Editar.cshtml
@model Argus.Models.ExameReferencia

<h2>Edição</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="../../Scripts/jquery-1.6.min.js" type="text/javascript"></script>
<script src="../../Scripts/jquery.maskedinput-1.3.min.js" type="text/javascript"></script>
<script src="../../Scripts/FuncoesGenericas.js" type="text/javascript"></script>

<script type="text/javascript">
    function SomenteNumero(num) {
        if (num < 48 || num > 57)
            return false;
    }
</script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
        @Html.TextBoxFor(model => model.CODIGO_ITEM, new { Type = "hidden" })
        <table>
        
        <tr>
        <td>@Html.LabelFor(model => model.CODIGO_EXAME, "Exame")</td>          
        <td>@Html.DropDownListFor(model => model.CODIGO_EXAME, ViewBag.ListaeExames as SelectList, new { Class = "listalistarequerida", Readonly="readonly" }) @Html.ValidationMessageFor(model => model.CODIGO_EXAME)</td>
        </tr>
  
        <tr>
        <td>@Html.LabelFor(model => model.DESCRICAO)</td>
        <td>@Html.TextBoxFor(model => model.DESCRICAO, new { maxlength = 60, Class = "textomediorequerido" }) @Html.ValidationMessageFor(model => model.DESCRICAO)</td>
        </tr>

        <tr>
        <td>@Html.LabelFor(model => model.UNIDADES)</td>
        <td>@Html.TextBoxFor(model => model.UNIDADES, new { Class = "textopequeno" }) @Html.ValidationMessageFor(model => model.UNIDADES)</td>
        </tr>
        
         <tr>
        <td>@Html.LabelFor(model => model.DE)</td>
        <td>@Html.TextBoxFor(model => model.DE, new { maxlength = 3, id = "de", Class = "textopequeno", OnKeyPress = "return SomenteNumero(event.keyCode)" }) @Html.ValidationMessageFor(model => model.DE)</td>
        </tr>

         <tr>
        <td>@Html.LabelFor(model => model.ATE)</td>
        <td>@Html.TextBoxFor(model => model.ATE, new { maxlength = 3, id = "ate", Class = "textopequeno", OnKeyPress = "return SomenteNumero(event.keyCode)" }) @Html.ValidationMessageFor(model => model.ATE)</td>
        </tr>             

        </table>
    
        <p> <input type="submit" value="Gravar" /> </p>
}

Code/Argus/Views/ExameReferencia/Eliminar.cshtml
@model Argus.Models.ExameReferencia

<h2>Eliminação</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())        
{    
        @Html.TextBoxFor(model => model.CODIGO_EXAME, new { Type = "hidden" })
        @Html.TextBoxFor(model => model.CODIGO_ITEM, new { Type = "hidden" })
        <table>
        
        <tr>
        <td>@Html.LabelFor(model => model.DESCRICAO)</td>
        <td>@Html.TextBoxFor(model => model.DESCRICAO, new { Readonly = "readonly" }) </td>
        </tr>
         
        </table>
    
        <p> <input type="submit" value="Eliminar" /> </p>
}

<div>
    @Html.ActionLink("Voltar", "Listar")
</div>

Code/Argus/Views/ExameReferencia/Incluir.cshtml
@model Argus.Models.ExameReferencia

<h2>Inclusão</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="../../Scripts/jquery-1.6.min.js" type="text/javascript"></script>
<script src="../../Scripts/jquery.maskedinput-1.3.min.js" type="text/javascript"></script>
<script src="../../Scripts/FuncoesGenericas.js" type="text/javascript"></script>

<script type="text/javascript">
function SomenteNumero(num) {
    if (num < 48 || num > 57)
        return false;
}
</script>


@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
        <table>
                
        <tr>
        <td>@Html.LabelFor(model => model.CODIGO_EXAME, "Exame")</td>          
        <td>@Html.DropDownListFor(model => model.CODIGO_EXAME, ViewBag.ListaeExames as SelectList, new { Class = "listalistarequerida" }) @Html.ValidationMessageFor(model => model.CODIGO_EXAME)</td>
        </tr>
  
        <tr>
        <td>@Html.LabelFor(model => model.DESCRICAO)</td>
        <td>@Html.TextBoxFor(model => model.DESCRICAO, new { maxlength = 60, Class = "textomediorequerido" }) @Html.ValidationMessageFor(model => model.DESCRICAO)</td>
        </tr>

        <tr>
        <td>@Html.LabelFor(model => model.UNIDADES)</td>
        <td>@Html.TextBoxFor(model => model.UNIDADES, new { Class = "textopequeno" }) @Html.ValidationMessageFor(model => model.UNIDADES)</td>
        </tr>
        
         <tr>
        <td>@Html.LabelFor(model => model.DE)</td>
        <td>@Html.TextBoxFor(model => model.DE, new { maxlength = 3, id = "de", Class = "textopequeno", OnKeyPress = "return SomenteNumero(event.keyCode)" }) @Html.ValidationMessageFor(model => model.DE)</td>
        </tr>

         <tr>
        <td>@Html.LabelFor(model => model.ATE)</td>
        <td>@Html.TextBoxFor(model => model.ATE, new { maxlength = 3, id = "ate", Class = "textopequeno", OnKeyPress = "return SomenteNumero(event.keyCode)" }) @Html.ValidationMessageFor(model => model.ATE)</td>
        </tr>             
        
        </table>
       
        <p><input type="submit" value="Gravar" /></p>
}

Code/Argus/Views/ExameReferencia/Listar.cshtml
@model IEnumerable<Argus.Models.ExameReferencia>

@{
    WebGrid grid = new WebGrid(source: Model, selectionFieldName: "SelectedRow", rowsPerPage: 20);
}

<script src="@Url.Content("~/Scripts/jquery.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.tabify.js")" type="text/javascript"></script>
<script src="../../Scripts/FuncoesGenericas.js" type="text/javascript"></script>
<link href="../../Content/webgrid.css" rel="stylesheet" type="text/css" />

<table>
    <tr>
        <td>
            @using (Html.BeginForm("Listar","ExameReferencia"))
            {
                <div class="textomedio">@Html.DisplayText("Informe a referência do exame:")</div>
                @Html.TextBox("pesquisa", "") 
                <input type="submit" value="Pesquisar" />
            }
        </td>
        <td  width="20%" align="center">
            @Html.ActionLink("Incluir", "Incluir")
        </td>
    </tr>
    <tr>
        <td colspan="2" width="100%">
            @grid.GetHtml(
                tableStyle: "webgrid",
                headerStyle: "webgrid-header",
                footerStyle: "webgrid-footer",
                alternatingRowStyle: "webgrid-alternating-row",
                selectedRowStyle: "webgrid-selected-row",
                rowStyle: "webgrid-row-style",
                mode: WebGridPagerModes.FirstLast | WebGridPagerModes.NextPrevious,
                firstText: "Primeiro",
                previousText: "Anterior",
                nextText: "Próximo",
                lastText: "Último",
                columns: grid.Columns(
                grid.Column("DESCRICAO", header: "Descrição", format: @<text><div class="colunanome">@item.DESCRICAO</div></text>),
                grid.Column("Editar", header: "Editar", format: @<text><div class="colunanomepequeno">@Html.ActionLink("Editar", "Editar", new { codigo = item.CODIGO_EXAME, codigoitem = item.CODIGO_ITEM })</div></text>, canSort: false),
                grid.Column("Eliminar", header: "Eliminar", format: @<text><div class="colunanomepequeno">@Html.ActionLink("Eliminar", "Eliminar", new { codigo = item.CODIGO_EXAME, codigoitem = item.CODIGO_ITEM  })</div></text>, canSort: false)
            )
            )
        </td>
    </tr>
</table>