Code/Argus/Models/MedicinaPrev.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.Data;


namespace Argus.Models
{
    public class MedicinaPrev
    {

        private Contexto db = new Contexto();

        [Key]
        public int CODIGO { get; set; }

        [ForeignKey("Raca")]
        [Display(Name = "Raça")]
        [Required(ErrorMessage = "Por favor preencher a raça")]
        public int CODIGO_RACA { get; set; }

        [Display(Name = "Prevenção")]
        [Required(ErrorMessage = "Por favor preencher a Prevenção")]
        public string DESCRICAO { get; set; }

       

        public virtual Raca Raca { get; set; }

        public void Incluir(MedicinaPrev medicinaprev)
        {
            db.MedicinaPrev.Add(medicinaprev);
            db.SaveChanges();
        }

        public void Atualizar(MedicinaPrev medicinaprev)
        {
            db.Entry(medicinaprev).State = EntityState.Modified;
            db.SaveChanges();
        }

        public void Eliminar(MedicinaPrev medicinaprev)
        {
            db.Entry(medicinaprev).State = EntityState.Deleted;
            db.SaveChanges();
        }

        public MedicinaPrev Busca(int id)
        {
            return db.MedicinaPrev.Find(id);
        }

        public List<MedicinaPrev> ListarMedicinaPrev(String pesquisa)
        {
            var medicinaprev = (from a in db.MedicinaPrev
                                  where a.DESCRICAO.StartsWith(pesquisa)
                                  select a).Take(50).ToList();
            return medicinaprev;
        }

    }
}

Code/Argus/Controllers/MedicinaPrevController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Argus.Models;
using System.IO;

namespace Argus.Controllers
{
    [Authorize]
    public class MedicinaPrevController : Controller
    {
        private Contexto db = new Contexto();

        public ActionResult Listar(String pesquisa = "")
        {
            MedicinaPrev medicinaprev = new MedicinaPrev();
            return View(medicinaprev.ListarMedicinaPrev(pesquisa));
        }

        public ActionResult Incluir()
        {
            ViewBag.ListarRaca = new SelectList(db.Raca, "CODIGO", "NOME");
            return View();
        }

        [HttpPost]
        public ActionResult Incluir(MedicinaPrev medicinaprev)
        {
            if (ModelState.IsValid)
            {
                medicinaprev.Incluir(medicinaprev);


                return RedirectToAction("Listar");
            }
            else
                return View(medicinaprev);
        }

        public ActionResult Editar(int codigo)
        {
            MedicinaPrev medicinaprev = db.MedicinaPrev.Find(codigo);
            ViewBag.ListarRaca = new SelectList(db.Raca, "CODIGO", "NOME");
            return View(medicinaprev);
        }

        [HttpPost]
        public ActionResult Editar(MedicinaPrev medicinaprev)
        {
            if (ModelState.IsValid)
            {
                medicinaprev.Atualizar(medicinaprev);
                return RedirectToAction("Listar");
            }
            else
                return View(medicinaprev);
        }

        public ActionResult Eliminar(int codigo)
        {
            MedicinaPrev medicinaprev = db.MedicinaPrev.Find(codigo);
            return View(medicinaprev);
        }

        [HttpPost]
        public ActionResult Eliminar(MedicinaPrev medicinaprev)
        {
            medicinaprev.Eliminar(medicinaprev);
            return RedirectToAction("Listar");
        }
    }
}

Code/Argus/Views/MedicinaPrev/Editar.cshtml
@model Argus.Models.MedicinaPrev

<h2>Edição</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

<head>

<script src="../../Scripts/jquery-1.6.min.js" type="text/javascript"></script>
<script src="../../Scripts/jquery.maskedinput-1.3.min.js" type="text/javascript"></script>
  
  <script type="text/javascript">
      jQuery(function () {
          $("#dt_nascimento").mask("99/99/9999");
      });

    </script>
</head>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
        <table>                
               
        <tr>
        <td>@Html.LabelFor(model => model.CODIGO_RACA, "Raça")</td>          
        <td>@Html.DropDownListFor(model => model.CODIGO_RACA, ViewBag.ListarRaca as SelectList) @Html.ValidationMessageFor(model => model.CODIGO_RACA)</td>
        </tr>
        
        <tr>
        <td>@Html.LabelFor(model => model.DESCRICAO)</td>      
        <td>@Html.TextAreaFor(model => model.DESCRICAO, new {cols = "40%" }) @Html.ValidationMessageFor(model => model.DESCRICAO)</td>  
        </tr>


        </table>
    
        <p> <input type="submit" value="Gravar" /> </p>
}

<div>
    @Html.ActionLink("Voltar", "Listar")
</div>

Code/Argus/Views/MedicinaPrev/Eliminar.cshtml
@model Argus.Models.MedicinaPrev

<h2>Eliminação</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{    
        <table>
        
        <tr>
        <td>@Html.LabelFor(model => model.DESCRICAO)</td>
        <td>@Html.TextBoxFor(model => model.DESCRICAO, new { Readonly = "readonly" }) </td>
        </tr>
         
        </table>
    
        <p> <input type="submit" value="Eliminar" /> </p>
}

<div>
    @Html.ActionLink("Voltar", "Listar")
</div>

Code/Argus/Views/MedicinaPrev/Incluir.cshtml
@model Argus.Models.MedicinaPrev

<h2>Inclusão</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="../../Scripts/jquery-1.6.min.js" type="text/javascript"></script>
<script src="../../Scripts/jquery.maskedinput-1.3.min.js" type="text/javascript"></script>
<script src="../../Scripts/FuncoesGenericas.js" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
        <table>
        
        <tr>
        <td>@Html.LabelFor(model => model.CODIGO_RACA, "Raça")</td>          
        <td>@Html.DropDownListFor(model => model.CODIGO_RACA, ViewBag.ListarRaca as SelectList, new { Class = "listarequerida" }) @Html.ValidationMessageFor(model => model.CODIGO_RACA)</td>
        </tr>     
                    
        <tr>
        <td>@Html.LabelFor(model => model.DESCRICAO)</td>      
        <td>@Html.TextAreaFor(model => model.DESCRICAO, new { maxlength = 60, Class = "observacaorequerida" }) @Html.ValidationMessageFor(model => model.DESCRICAO)</td>  
        </tr>

        </table>
          
        <p><input type="submit" value="Gravar" /></p>    
}



 

Code/Argus/Views/MedicinaPrev/Listar.cshtml
@model IEnumerable<Argus.Models.MedicinaPrev>

@{
    WebGrid grid = new WebGrid(source: Model, selectionFieldName: "SelectedRow", rowsPerPage: 20);
}
<script src="@Url.Content("~/Scripts/jquery.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.tabify.js")" type="text/javascript"></script>
<script src="../../Scripts/FuncoesGenericas.js" type="text/javascript"></script>
<link href="../../Content/webgrid.css" rel="stylesheet" type="text/css" />

<table>
    <tr>
        <td>
            @using (Html.BeginForm("Listar","MedicinaPrev")) {
                <div class="textomedio">@Html.DisplayText("Informe a descrição da medicina preventiva:")</div>
                @Html.TextBox("pesquisa", "") 
                <input type="submit" value="Pesquisar" />                
            }
        </td>
        <td  width="20%" align="center">
            @Html.ActionLink("Incluir", "Incluir")
        </td>
    </tr>
    <tr>
    <td colspan="2" width="100%">
        @grid.GetHtml(
            tableStyle: "webgrid",
            headerStyle: "webgrid-header",
            footerStyle: "webgrid-footer",
            alternatingRowStyle: "webgrid-alternating-row",
            selectedRowStyle: "webgrid-selected-row",
            rowStyle: "webgrid-row-style",
            mode: WebGridPagerModes.FirstLast | WebGridPagerModes.NextPrevious,
            firstText: "Primeiro",
            previousText: "Anterior",
            nextText: "Próximo",
            lastText: "Último",
            columns: grid.Columns(
            grid.Column("RACA", header: "Raça", format: @<text><div class="colunanome">@item.Raca.NOME</div></text>),
            grid.Column("DESCRICAO", header: "Prevenção", format: @<text><div class="colunaobservacao">@item.DESCRICAO</div></text>),
            grid.Column("Editar", header: "Editar", format: @<text><div class="colunanomepequeno">@Html.ActionLink("Editar", "Editar", new { codigo = item.CODIGO })</div></text>, canSort: false),
            grid.Column("Eliminar", header: "Eliminar", format: @<text><div class="colunanomepequeno">@Html.ActionLink("Eliminar", "Eliminar", new { codigo = item.CODIGO })</div></text>, canSort: false)
        )
        )
    </td>
    </tr>
</table>